<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<!--<GeneratePackageOnBuild>true</GeneratePackageOnBuild>-->
		<!--<Version>1.1.6</Version>-->
		<Authors>SourceCrafter</Authors>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<Description>Helpers for SourceCrafter.DependencyInjection</Description>
		<PackageTags>dependency-injection;source-generator</PackageTags>
		<PackageOutputPath>../packaging</PackageOutputPath>
	</PropertyGroup>
	
	<ItemGroup>
	  	<None Remove="bin\Debug\netstandard2.0\SourceCrafter.DependencyInjection.Utils.dll" />
			<Compile Remove="**\*.cs" />
			<Compile Remove="obj\**" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\SourceCrafter.DependencyInjection.Shared\**\*.cs" Pack="true" PackagePath="contentFiles/cs/netstandard2.0/SourceCrafter.DependencyInjection" buildAction="Compile" />
		<None Include="**\*.cs" Pack="true" PackagePath="contentFiles/cs/netstandard2.0/SourceCrafter.DependencyInjection" buildAction="Compile" />
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Remove="obj\**" />
	  <None Remove="obj\**" />
	</ItemGroup>

</Project>
