using Microsoft.CodeAnalysis;
using SourceCrafter.DependencyInjection.Generation;
using System.Linq;
using System.Text;
using System.Threading;

namespace SourceCrafter.DependencyInjection.Partial.ServiceCatalog;

/// <summary>
/// Parcial de ejemplo: por cada contenedor anade una declaracion <c>partial</c> mas con un
/// catalogo de lo que ese contenedor sabe resolver.
///
/// <para>
/// Muestra el uso de los tres niveles de acceso: los metadatos planos
/// (<see cref="ServiceInfo.Lifetime"/>), el simbolo de cada servicio
/// (<see cref="ServiceInfo.ExportType"/>) y la <c>Compilation</c> completa.
/// </para>
/// </summary>
public sealed class ServiceCatalogPartial : ServiceProviderPartial
{
    public override void AnalyzeContainer(
        ServiceProviderInfo container,
        PartialContribution contribution,
        CancellationToken cancelToken)
    {
        // Sin servicios no hay catalogo que emitir, y el contenedor puede ni siquiera tener
        // archivo propio.
        if (container.Services.Count == 0) return;

        // Se resuelve una vez, no por servicio: GetTypeByMetadataName recorre las referencias.
        var disposable = container.Compilation.GetTypeByMetadataName("System.IDisposable");

        StringBuilder code = new("// <auto-generated/>\n#nullable enable\n");

        if (container.Namespace is { Length: > 0 } ns)
        {
            code.Append("namespace ").Append(ns).Append(";\n\n");
        }

        // Se reutilizan los mismos modificadores y nombre de tipo que emite el contenedor:
        // cualquier otra combinacion daria CS0261 o CS0262 al fusionar los partials.
        code.Append(container.Modifiers).Append(' ').Append(container.TypeName).Append(@"
{
    /// <summary>Descripcion de cada servicio registrado, en orden de declaracion.</summary>
    public static global::System.Collections.Generic.IReadOnlyList<string> ServiceCatalog { get; } =
    [");

        foreach (var service in container.Services)
        {
            cancelToken.ThrowIfCancellationRequested();

            code.Append("\n\t\t\"")
                .Append(service.Lifetime)
                .Append(' ')
                .Append(Escape(service.ExportTypeFullName));

            if (service.Key is { Length: > 0 } key) code.Append(" key=").Append(Escape(key));

            // Esto es lo que el formato plano anterior no permitia: preguntarle al modelo
            // semantico en vez de reinterpretar cadenas.
            if (service.ExportType is { } exportType)
            {
                if (exportType.TypeKind == TypeKind.Interface) code.Append(" iface");

                if (disposable is not null
                    && exportType.AllInterfaces.Contains(disposable, SymbolEqualityComparer.Default))
                {
                    code.Append(" disposable");
                }
            }

            code.Append(" -> ")
                .Append(service.MemberName is { Length: > 0 } member ? Escape(member) : "<inlined>")
                .Append("\",");
        }

        code.Append(@"
    ];
}
");

        contribution.AddSource(container.ClassName + ".ServiceCatalog", code.ToString());
    }

    /// <summary>
    /// El texto acaba dentro de un literal normal: una comilla o una barra sin escapar
    /// rompen la compilacion del consumidor.
    /// </summary>
    private static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
