<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<!--<GeneratePackageOnBuild>true</GeneratePackageOnBuild>-->
		<!--<Version>1.1.6</Version>-->
		<Authors>SourceCrafter</Authors>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<Description>Helpers for SourceCrafter.DependencyInjection</Description>
		<PackageTags>dependency-injection;source-generator</PackageTags>
		<PackageOutputPath>../packaging</PackageOutputPath>
		<Configurations>Debug;Release;Pack;DEBUG_SG</Configurations>	
	</PropertyGroup>


	<ItemGroup>
		<Compile Include="..\SourceCrafter.DependencyInjection.Shared\**\*.cs">
			<Link>Shared\%(RecursiveDir)%(Filename)%(Extension)</Link>
		</Compile>
	</ItemGroup>
	
	<ItemGroup>
		<None Include="JsonSettingAttribute.cs" Pack="true" PackagePath="contentFiles/cs/netstandard2.0/SourceCrafter.DependencyInjection" buildAction="Compile" />
	</ItemGroup>

</Project>
