// <auto-generated/>
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Net.Http;
global using System.Threading;
global using System.Threading.Tasks;
global using DependencyKeyInt = (Lifetime lifetime, int typeHash, int keyHash);
global using FirstLevelDependencyKeyInt = (int typeHash, int keyHash);
global using DependencyKey = (Lifetime lifetime, string type, string key);
global using FirstLevelDependencyKey = (string type, string key);
