using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using SourceCrafter.DependencyInjection;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Text;
using System.Xml.Linq;

#pragma warning disable CA1050 // Declarar tipos en espacios de nombres
internal partial class ServiceProviders
#pragma warning restore CA1050 // Declarar tipos en espacios de nombres
{
    private sealed class Emitter(
        string metadataLongName,
        string? nameSpace,
        string containerFullTypeName,
        string modifiers,
        bool isInterfaceProvider,
        bool implementsServiceProvider,
        bool generateServiceProviderApi,
        bool hasUserEnvironmentName,
        string className,
        string typeName,
        string envName,
        int asyncScopedDisposable,
        int asyncSingletonDisposable,
        int asyncScopedAsyncDisposable,
        int asyncSingletonAsyncDisposable,
        int scopedAsyncDisposable,
        int singletonAsyncDisposable,
        Disposability containerDisposability,
        Disposability scopedDisposability,
        DependencyDictionary dependencyValueBuilders,
        Dictionary<DependencyKey, MemberBuilder> dependencyMemberBuilder,
        HashSet<Diagnostic> diagnostics,
        HashSet<ResolverBuilder> genericResolvers) : IEquatable<Emitter>
    {
        internal readonly HashSet<Diagnostic> Diagnostics = diagnostics;
        internal readonly DependencyDictionary DependencyValueBuilders = dependencyValueBuilders;
        internal readonly string ContainerFullTypeName = containerFullTypeName;
        internal readonly string ClassName = className;

        /// <summary>
        /// Un contenedor solo puede reclamar llamadas interceptables si expone una
        /// superficie que interceptar: o implementa <c>IServiceProvider</c> (y por tanto
        /// hereda los metodos de extension) o genera la API generica propia.
        /// </summary>
        internal bool EmitsInterceptors => implementsServiceProvider || generateServiceProviderApi;

        string GetFileName(Dictionary<string, byte> uniqueName)
        {
            var existing = metadataLongName;
            ref var count = ref CollectionsMarshal.GetValueRefOrAddDefault(uniqueName, metadataLongName, out var exists);
            if (exists) count += 1;
            return exists ? existing + "_" + count : existing;
        }

        internal void Emit(
            Dictionary<string, byte> uniqueNames,
            Dictionary<FirstLevelDependencyKey, Interceptor> interceptors,
            ref bool addTasksExtensions,
            ref int interceptorsCount,
            out string fileName,
            out string codeStr)
        {
            StringBuilder code = new("// <auto-generated/>\n#nullable enable\n");

            fileName = GetFileName(uniqueNames);

            // Los miembros se renderizan primero, a un buffer aparte: el contenedor
            // necesita saber que candados hay que inicializar y si algun resolver consume
            // el token antes de poder declarar su constructor y sus interfaces.
            ContainerRenderContext ctx = new();
            StringBuilder members = new();

            foreach (var memberResolver in dependencyMemberBuilder.Values)
            {
                memberResolver.BuildAndExpose(members, ctx);
            }

            // No se muta el parámetro capturado: Equals/GetHashCode deben seguir
            // reflejando el valor parseado, no el derivado en tiempo de emisión.
            var effectiveDisposability = (Disposability)Math.Max((byte)scopedDisposability, (byte)containerDisposability);

            // El propio CancellationTokenSource es desechable: un contenedor que lo use
            // tiene que liberarlo aunque ninguno de sus servicios sea desechable, o el
            // registro de cancelacion se queda colgando.
            if (ctx.UsesLifetimeToken && effectiveDisposability is Disposability.None)
                effectiveDisposability = Disposability.Disposable;

            // Los servicios resueltos de forma as\u00edncrona necesitan TryDispose/TryDisposeAsync
            // para desenvolver el valor cacheado, sean IDisposable o IAsyncDisposable.
            if (asyncSingletonAsyncDisposable + asyncScopedAsyncDisposable
                + asyncSingletonDisposable + asyncScopedDisposable > 0)
            {
                if (!addTasksExtensions) addTasksExtensions = true;

                code.Append(@"using global::SourceCrafter.DependencyInjection.Extensions;

");
            }

            if (nameSpace is { } ns)
            {
                code.Append("namespace ").Append(ns).Append(@";

");
            }

            code.AppendLine(generatedCodeAttribute)
                .Append(modifiers)
                .AddSpace()
                .Append(typeName);

			AddDisposabilityInterface(code, effectiveDisposability, isInterfaceProvider);

			if (!hasUserEnvironmentName)
			{
				// El nombre de la variable se expone como constante y su lectura se hace
				// una sola vez: antes se consultaba el entorno en cada acceso.
				if (envName.StartsWith("\"", StringComparison.Ordinal))
				{
					code.Append(@"
	public const string EnvironmentVariableName = ").Append(envName).Append(@";

	public static string EnvironmentName { get; } = global::System.Environment.GetEnvironmentVariable(EnvironmentVariableName) ?? ""Development"";
");
				}
				else
				{
					code.Append(@"
	public static string EnvironmentName { get; } = global::System.Environment.GetEnvironmentVariable(").Append(envName).Append(@") ?? ""Development"";
");
				}
			}

			// Los miembros se renderizan aparte para poder emitir antes el constructor,
			// que necesita conocer los candados de instancia que ellos declaran.
			List<string> scopedMembers = ctx.ScopedMembers;
			List<DisposeBuilder> scopedDisposers = ctx.ScopedDisposers, singletonDisposers = ctx.SingletonDisposers;

			// Liberadores que exigen 'await'; los sincronos no obligan a marcar el metodo async.
			int scopedAwaitCount = asyncScopedAsyncDisposable + asyncScopedDisposable + scopedAsyncDisposable,
				singletonAwaitCount = asyncSingletonAsyncDisposable + asyncSingletonDisposable + singletonAsyncDisposable;

			bool isDisposable = effectiveDisposability > Disposability.None,
				usesLifetimeToken = ctx.UsesLifetimeToken,
				hasScopedDisposers = scopedDisposers.Count > 0 && scopedDisposability > Disposability.None,
				scopedDisposeIsAsync = scopedDisposability > Disposability.Disposable,
				containerDisposeIsAsync = effectiveDisposability > Disposability.Disposable;

			string scopedDisposeMethodName = scopedDisposeIsAsync ? "ScopedDisposeAsync" : "ScopedDispose",
				containerDisposeMethodName = containerDisposeIsAsync ? "DisposeAsync" : "Dispose",
				containerDisposeReturnType = containerDisposeIsAsync ? "global::System.Threading.Tasks.ValueTask " : "void ";

			if (isDisposable)
			{
				code.Append(@"
	private bool _disposed = false;
");
			}

			// Un unico token para todo el proveedor. Se copia una sola vez a un campo de
			// solo lectura: la propiedad CancellationTokenSource.Token revalida el estado
			// en cada lectura y lanza ObjectDisposedException una vez liberada la fuente,
			// cosa que ocurre en Dispose mientras los resolvers pueden seguir invocandose.
			// La copia no asigna memoria: CancellationToken es una estructura.
			if (usesLifetimeToken)
			{
				code.Append(@"
	private readonly global::System.Threading.CancellationTokenSource ").Append(ResolverRenderer.LifetimeCtsFieldName).Append(@";

	private readonly global::System.Threading.CancellationToken ").Append(ResolverRenderer.LifetimeTokenFieldName).Append(@";
");
			}

			AppendConstructor(code, ctx, usesLifetimeToken);

			AppendEnsureLockHelper(code, ctx);

			AppendSingletonLock(code, ctx);

			code.Append(members);

			if (scopedMembers.Count > 0)
			{
				code.Append(@"
	private ").Append(typeName).Append(@" _root = default!;

	public virtual ").Append(typeName).Append(@" Root => this;

	public virtual Scoped CreateScope() => new() { _root = this };

	public class Scoped : ").Append(typeName).Append(@"
	{
		public override ").Append(typeName).Append(@" Root => _root;

		public override Scoped CreateScope() => new() { _root = _root };
");

				// Un ambito nunca debe liberar los singletons de la raiz: por eso
				// redefine el metodo en vez de heredarlo (antes lo ocultaba con 'new',
				// lo que provocaba CS0108 y liberaba de mas al tipar como base).
				if (isDisposable)
				{
					code.Append(@"
		public override ").Append(containerDisposeReturnType).Append(containerDisposeMethodName).Append(@"()
		{
			if (_disposed) return").Append(containerDisposeIsAsync ? " default;" : ";").Append(@"

			_disposed = true;
");

					if (usesLifetimeToken)
						code.Append(@"
			__lifetimeCts.Cancel();
			__lifetimeCts.Dispose();
");

					if (hasScopedDisposers)
					{
						code.Append(@"
			");

						if (containerDisposeIsAsync && scopedDisposeIsAsync) code.Append("return ");

						code.Append(scopedDisposeMethodName).Append("();");
					}

					if (containerDisposeIsAsync && !(hasScopedDisposers && scopedDisposeIsAsync))
						code.Append(@"

			return default;");

					code.Append(@"
		}
");
				}

				code.Append(@"	}
");
			}

			// Ayudante sin guardia: lo invocan tanto la raiz como cada ambito.
			if (hasScopedDisposers)
			{
				var singleReturn = scopedDisposeIsAsync && scopedDisposers.Count == 1 && scopedAwaitCount == 1;

				code.Append(@"
	private ");

				if (!singleReturn && scopedAwaitCount > 0) code.Append("async ");

				code.Append(scopedDisposeIsAsync ? "global::System.Threading.Tasks.ValueTask " : "void ")
					.Append(scopedDisposeMethodName).Append(@"()
	{");

				AppendDisposers(code, scopedDisposers, singleReturn);

				if (scopedDisposeIsAsync && !singleReturn && scopedAwaitCount == 0)
					code.Append(@"

		return default;");

				code.Append(@"
	}
");
			}

			if (isDisposable)
			{
				var scopedCallAwaits = hasScopedDisposers && scopedDisposeIsAsync;

				int itemCount = singletonDisposers.Count + (hasScopedDisposers ? 1 : 0),
					awaitCount = singletonAwaitCount + (scopedCallAwaits ? 1 : 0);

				var singleReturn = containerDisposeIsAsync && itemCount == 1 && awaitCount == 1;

				// En un metodo 'async' no se puede escribir 'return default;', aunque
				// devuelva ValueTask: la maquina de estados exige 'return;'.
				var isAsyncMethod = !singleReturn && awaitCount > 0;

				code.Append(@"
	public virtual ");

				if (isAsyncMethod) code.Append("async ");

				code.Append(containerDisposeReturnType).Append(containerDisposeMethodName).Append(@"()
	{
		if (_disposed) return").Append(containerDisposeIsAsync && !isAsyncMethod ? " default;" : ";").Append(@"

		_disposed = true;
");

				if (usesLifetimeToken)
					code.Append(@"
		__lifetimeCts.Cancel();
		__lifetimeCts.Dispose();
");

				AppendDisposers(code, singletonDisposers, singleReturn && !hasScopedDisposers);

				if (hasScopedDisposers)
				{
					code.Append(@"
		");

					if (scopedCallAwaits) code.Append(singleReturn ? "return " : "await ");

					code.Append(scopedDisposeMethodName).Append("();");
				}

				if (containerDisposeIsAsync && !singleReturn && awaitCount == 0)
					code.Append(@"

		return default;");

				code.Append(@"
	}
");
			}

            var emitGenericApi = generateServiceProviderApi && genericResolvers.Count > 0;

            if (implementsServiceProvider || emitGenericApi)
            {
                code.Append(@"
    #region IServiceProvider compatibility
");

                // Solo obligatorio cuando el contenedor declara la interfaz.
                if (implementsServiceProvider)
                    code.Append(@"
    object? global::System.IServiceProvider.GetService(global::System.Type serviceType) => throw new global::System.NotImplementedException();
");

                if (emitGenericApi)
                {
                    foreach (var genericResolver in genericResolvers)
                        genericResolver.GenericMemberSignature(code);

                    // Un sitio de llamada sin clave que pide *todos* los servicios de un tipo
                    // se sirve tambien con los registros que si tienen clave: es lo que hace
                    // el fallback de CollectMsDIServiceCalls. Sin esta declaracion ese sitio
                    // no compila (CS1061) y el fallback queda inalcanzable.
                    foreach (var asyncKind in genericResolvers
                        .Where(r => r.Key.key != "")
                        .Select(r => r.AsyncKind)
                        .Distinct()
                        .Where(kind => !genericResolvers.Any(r => r.Key.key == "" && r.AsyncKind == kind))
                        .OrderBy(kind => kind))
                    {
                        ResolverBuilder.AppendSignature(code, asyncKind, false, true);
                    }
                }

                code.Append(@"
    #endregion");
            }
            code.Append(@"
}
");

            if (EmitsInterceptors && interceptors.Count > 0)
            {
                code.Append(@" 
public static class ").Append(typeName).Append(@"Extensions
{");

                foreach (var item in interceptors.Values)
                {
                    item.Append(code, ClassName, ref interceptorsCount);
                }

                code.Append('}');
            }

            codeStr = NormalizeLayout(code);
        }

        /// <summary>
        /// Unifica el sangrado a tabuladores (4 espacios = 1 tabulador), elimina los
        /// espacios finales y normaliza los saltos de linea. Se hace en una sola pasada
        /// al final para no depender de la disciplina de cada literal de la plantilla,
        /// que mezclaba tabuladores y espacios.
        /// </summary>
        internal static string NormalizeLayout(StringBuilder code)
        {
            var source = code.ToString();

            StringBuilder result = new(source.Length);

            var start = 0;

            while (true)
            {
                var newLine = source.IndexOf('\n', start);
                var lineEnd = newLine < 0 ? source.Length : newLine;

                var line = source.Substring(start, lineEnd - start).TrimEnd('\r', ' ', '\t');

                var width = 0;
                var first = 0;

                for (; first < line.Length; first++)
                {
                    if (line[first] == ' ') width++;
                    else if (line[first] == '\t') width += 4 - (width % 4);
                    else break;
                }

                if (first < line.Length)
                    result.Append('\t', width / 4)
                        .Append(' ', width % 4)
                        .Append(line, first, line.Length - first);

                if (newLine < 0) break;

                result.Append("\r\n");
                start = newLine + 1;
            }

            return result.ToString();
        }


        /// <summary>
        /// Inicializa la fuente de cancelacion junto con su token. Solo se emite si hay algo
        /// que inicializar, para no chocar con un constructor sin parametros del usuario.
        /// Los candados de instancia ya no se crean aqui: ver <see cref="AppendEnsureLockHelper"/>.
        /// </summary>
        void AppendConstructor(StringBuilder code, ContainerRenderContext ctx, bool usesLifetimeToken)
        {
            if (!usesLifetimeToken) return;

            code.Append(@"
    public ").Append(ClassName).Append(@"()
    {");

            code.Append(@"
        ").Append(ResolverRenderer.LifetimeCtsFieldName).Append(@" = new();
        ").Append(ResolverRenderer.LifetimeTokenFieldName).Append(" = ")
                .Append(ResolverRenderer.LifetimeCtsFieldName).Append(".Token;");

            code.Append(@"
    }
");
        }

        /// <summary>
        /// Crea un candado de instancia la primera vez que se necesita.
        /// <para>
        /// Se usa <c>Interlocked.CompareExchange</c> y no <c>??=</c>: este ultimo se expande
        /// a leer-comprobar-escribir, que no es atomico, y dos hilos pueden acabar con
        /// candados distintos y por tanto sin exclusion alguna.
        /// </para>
        /// <para>
        /// El camino rapido de cada resolver (<c>if (_x is not null) return _x;</c>) no llega
        /// aqui, asi que el coste en caliente es cero; a cambio, crear un ambito deja de
        /// pagar un candado por cada servicio scoped declarado.
        /// </para>
        /// </summary>
        static void AppendEnsureLockHelper(StringBuilder code, ContainerRenderContext ctx)
        {
            if (ctx.InstanceLockFields.Count == 0) return;

            var lockType = ctx.InstanceLockTypeName;

            code.Append(@"
    private static ").Append(lockType).Append(' ').Append(ResolverRenderer.EnsureLockMethodName)
                .Append("(ref ").Append(lockType).Append(@"? location)
    {
        var current = global::System.Threading.Volatile.Read(ref location);

        if (current is not null) return current;

        var created = new ").Append(lockType).Append(@"();

        return global::System.Threading.Interlocked.CompareExchange(ref location, created, null) ?? created;
    }
");
        }

        /// <summary>
        /// Candado unico compartido por todos los singletons sincronos del contenedor.
        /// <para>
        /// Un singleton no puede vigilarse con <c>lock(this)</c>: su campo de respaldo es
        /// <c>static</c>, asi que dos instancias distintas del contenedor bloquearian objetos
        /// distintos y no habria exclusion alguna. Necesita un objeto igualmente estatico.
        /// </para>
        /// <para>
        /// Compartirlo entre todos los singletons es seguro porque el camino lento resuelve
        /// fuera del <c>lock</c> toda dependencia que a su vez adquiera candados, de modo que
        /// nunca se retiene este candado mientras se espera otro.
        /// </para>
        /// </summary>
        static void AppendSingletonLock(StringBuilder code, ContainerRenderContext ctx)
        {
            if (!ctx.NeedsSingletonLock) return;

            code.Append(@"
    private static readonly ").Append(ctx.InstanceLockTypeName).Append(' ')
                .Append(ResolverRenderer.SingletonLockFieldName).Append(@" = new();
");
        }

        /// <summary>
        /// Emite los liberadores en orden inverso al de construccion. Si el metodo
        /// devuelve <c>ValueTask</c> y solo hay un liberador que requiere espera, se
        /// emite en forma de <c>return</c> para no generar una maquina de estados.
        /// </summary>
        static void AppendDisposers(StringBuilder code, List<DisposeBuilder> disposers, bool singleReturn)
        {
            if (singleReturn && disposers.Count == 1)
            {
                disposers[0](code, false);
                return;
            }

            for (var i = disposers.Count - 1; i >= 0; i--) disposers[i](code, true);
        }

        void AddDisposabilityInterface(StringBuilder code, Disposability disposability, bool isInterface = false)
        {
            switch (disposability)
            {
                case Disposability.Disposable:

                    code.Append(" :");

                    if (isInterface) code.Append(" I").Append(typeName).Append(',');

                    code.Append(@" global::System.IDisposable
{");

                    break;

                case Disposability.AsyncDisposable:

                    code.Append(" :");

                    if (isInterface) code.Append(" I").Append(typeName).Append(',');

                    code.Append(@" global::System.IAsyncDisposable
{");

                    break;

                default:

                    if (isInterface) code.Append(" : I").Append(typeName);

                    code.Append(@"
{");

                    break;
            }
        }

        internal static void AddOrUpdateIntercerceptor(
            Dictionary<FirstLevelDependencyKey, Interceptor> interceptors,
            HashSet<InterceptableLocation> acknowledged,
            InvokeInfo serviceCall,
            bool multiple,
            ResolverBuilder resolver)
        {
            var key = (serviceCall.ReturnType, serviceCall.Key);

            var element = new InterceptorElement(
                serviceCall.AsyncKind > 0,
                AppendDependency,
                resolver.Key,
                [.. resolver.AsyncLocalResolvers.Keys]);

            var interceptor = CollectionsMarshal.GetValueRefOrAddDefault(interceptors, key, out var exists) ??=
                new(key,
                    serviceCall.MethodName,
                    multiple,
                    serviceCall.AsyncKind,
                    serviceCall.ReturnType,
                    serviceCall.IsKeyed,
                    serviceCall.Interceptor,
                    element);

            acknowledged.Add(serviceCall.Interceptor);

            interceptor.Locations.Add(serviceCall.Interceptor);

            if (exists && multiple)
            {
                if (interceptor.AsyncKind < resolver.AsyncKind)
                    interceptor.AsyncKind = resolver.AsyncKind;
                interceptor.IsKeyed = serviceCall.IsKeyed;

                // Solo se acumula mientras se recorren los resolvedores del sitio que
                // construyo la lista. Otro sitio de llamada a la misma clave reutiliza el
                // interceptor y aporta su localizacion, pero repetir aqui sus resolvedores
                // devolvia el array duplicado (2N elementos) a *ambos* llamadores.
                if (interceptor.BuiltFrom.Equals(serviceCall.Interceptor))
                    interceptor.AppendInterceptorValue.Add(element);
            }

            void AppendDependency(StringBuilder code, bool useAsync)
            {
                resolver.AppendValue(code, useAsync, true);
            }
        }

        public override bool Equals(object? obj)
        {
            return Equals(obj as Emitter);
        }

        public bool Equals(Emitter? other)
        {
            return other is not null
                    && (ReferenceEquals(other, this)
                        || other.EqualsTo(this, containerDisposability, isInterfaceProvider, implementsServiceProvider, generateServiceProviderApi, hasUserEnvironmentName, nameSpace, typeName, modifiers, envName, dependencyMemberBuilder));
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private bool EqualsTo(
            Emitter other,
            Disposability _containerDisposability,
            bool _isInterfaceProvider,
            bool _implementsServiceProvider,
            bool _generateServiceProviderApi,
            bool _hasUserEnvironmentName,
            string? _nameSpace,
            string _typeName,
            string _modifiers,
            string _envName,
            Dictionary<DependencyKey, MemberBuilder> _dependencyMemberBuilder)
        {
            return _containerDisposability == containerDisposability
                && _isInterfaceProvider == isInterfaceProvider
                && _implementsServiceProvider == implementsServiceProvider
                && _generateServiceProviderApi == generateServiceProviderApi
                && _hasUserEnvironmentName == hasUserEnvironmentName
                && _nameSpace == nameSpace
                && _typeName == typeName
                && other.ClassName == ClassName
                && _modifiers == modifiers
                && _envName == envName
                && _dependencyMemberBuilder.Count == dependencyMemberBuilder.Count
                && dependencyMemberBuilder.All(kv => _dependencyMemberBuilder.TryGetValue(kv.Key, out var found) && found.Equals(kv.Value));
        }

        public override int GetHashCode()
        {
            HashCode hashCode = new();

            hashCode.Add(containerDisposability);
            hashCode.Add(isInterfaceProvider);
            hashCode.Add(implementsServiceProvider);
            hashCode.Add(generateServiceProviderApi);
            hashCode.Add(hasUserEnvironmentName);
            hashCode.Add(nameSpace);
            hashCode.Add(typeName);
            hashCode.Add(ClassName);
            hashCode.Add(modifiers);
            hashCode.Add(envName);

            foreach (var item in dependencyMemberBuilder.Values)
            {
                hashCode.Add(item.GetHashCode());
            }

            return hashCode.ToHashCode();
        }
    }
    sealed class EmitterEqualityComparer : IEqualityComparer<Emitter>
    {
        internal static readonly EmitterEqualityComparer Default = new();

        public bool Equals(Emitter? x, Emitter? y)
        {
            return ReferenceEquals(x, y) || (x is not null && x.Equals(y));
        }

        public int GetHashCode([DisallowNull] Emitter other)
        {
            return other.GetHashCode();
        }
    }
}
